server:
  port: 7070

spring:
  application:
    name: ms-costumer

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#keycloak:
#  auth-server-url: ${KEYCLOAK_URL:http://localhost:8081}
#  autodetect-bearer-only: true
#  credentials:
#    secret: RQ7Fdx7IHKHjbQu8hVDjmKINk8DlLQqp
#  realm: software
#  resource: backend
#  ssl-required: external
#  use-resource-role-mappings: false
#  security-constraints:
#    - authRoles:
#        - ADMIN
#      security-collections:
#        - name: SERVICIOS DE ADMINISTRADOR
#          patterns:
#            - /v1/api/currency/all
#          omitted-methods:
#            - OPTIONS
#    - auth-roles:
#        - USER
#      security-collections:
#        - name: SERVICIOS DE USUARIO
#          patterns:
#            - /v1/api/currency
#          omitted-methods:
#            - OPTIONS
